//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerreraNueva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopciones
    {
        public int PerroId { get; set; }
        public int ClienteId { get; set; }
        public int EmpleadoId { get; set; }
        public System.DateTime FechaEntrega { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Perros Perros { get; set; }
    }
}
